  <!-- Start Header-->  
     <header id="header" class="alfix">
		<div class="pw">
				<h1 id="classlogo">XMLHttpRequest Quiz</h1>
				<nav id="navigation"><a href="#" id="menu">Menu</a>
						<ul>
								<li><a href="index.php" title="Home">Home</a></li><li><a href="topic.php" title="About Topic">About Topic</a></li><li><a href="quiz.php" title="Quiz">Quiz</a></li><li><a href="login.php" title="Admin">Admin</a></li>
						</ul>
				</nav>
		</div>
</header>